### ISSUE TITLE
Code files in /headOfStateComponent

### ISSUE THREAD

**Issue by meesterbaumer** [NSS-Day-Cohort-42/hello-world-beautiful-balrogs#27]

**Comment by gavinschriver** [comment]
- [ ] headOfStateHTMLRepresenter.js

- [ ] headOfStateList.js

**Comment by gavinschriver** [comment]
**headOfStateHTMLRepresenter.js**
-export function to ./headOfStateList.js

**headOfStateList.js**
-import function defined in headOfStateRepresenter.js
-export function to 

- [ ] icelandMain.js
- [ ] tuvaluMain.js
- [ ] romaniaMain.js
- [ ] fijiMain.js
