### ISSUE TITLE
Code files in countries/taiwan

### ISSUE THREAD

**Issue by gavinschriver** [NSS-Day-Cohort-42/hello-world-beautiful-balrogs#30]

**Comment by gavinschriver** [comment]
- [ ] taiwanLandmarkProvider.js
- [ ] taiwanCityProvider.js
- [ ] taiwanHeadsOfStateProvider.js
- [ ] taiwanIntroProvider.js
- [ ] taiwanMain.js

**Comment by gavinschriver** [comment]
export function defined in taiwanLandmarkProvider.js to ./scripts/landmarkComponent/landmarkList.js
export function defined in taiwanCityProvider.js to ./scripts/cityComponent/cityList.js
export function defined in taiwanHeadOfStateProvider.js to ./scripts/headOfStateComponent/headOfStateList.js
export function defined in taiwanIntroProvider.js to ./scripts/introComponent/introList.js
import functions defined in introList.js, cityList.js, landmarkList.js and headOfState.js to taiwanMain.js

**Comment by skratz17** [comment]
We did this and I am closing it so it goes off of my dashboard on Github.
